import { useCallback, useEffect, useState } from 'react';
import { Check, Coins, Copy, Eye, EyeOff, Pencil, Plus, RefreshCw, Shield, Trash2, Wallet, X } from 'lucide-react';
import { apiRequest } from '@/services/apiClient';
import { useAuth, type AuthUser } from '@/auth/AuthContext';

type Transaction = { id: string; amountCents: number; type: string; description: string; createdAt: string };
type Recharge = { id: string; amountCents: number; status: string; note: string; createdAt: string; user?: AuthUser };
type SystemApi = { id: string; name: string; provider: string; baseUrl: string; apiKey: string; enabled: boolean };
type Pricing = { id: string; apiId: string; modelId: string; displayName: string; category: string; billingUnit: string; unitPriceCents: number; enabled: boolean };

const yuan = (cents: number) => `¥${(Number(cents || 0) / 100).toFixed(2)}`;
const field = 'w-full px-3 py-2 bg-dark-900 border border-dark-600 rounded text-sm text-white focus:outline-none focus:border-primary-500';

export default function AccountCenter({ mode, onClose }: { mode: 'billing' | 'admin'; onClose: () => void }) {
  const { user, refresh } = useAuth();
  const [balance, setBalance] = useState(0);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [recharges, setRecharges] = useState<Recharge[]>([]);
  const [apis, setApis] = useState<SystemApi[]>([]);
  const [pricing, setPricing] = useState<Pricing[]>([]);
  const [users, setUsers] = useState<AuthUser[]>([]);
  const [amount, setAmount] = useState('');
  const [note, setNote] = useState('');
  const [message, setMessage] = useState('');
  const [showKeys, setShowKeys] = useState<Record<string, boolean>>({});
  const [apiForm, setApiForm] = useState({ name: '', provider: '', baseUrl: '', apiKey: '' });
  const [priceForm, setPriceForm] = useState({ apiId: '', modelId: '', displayName: '', category: 'text', billingUnit: 'request', priceYuan: '' });
  const [editingApiId, setEditingApiId] = useState<string | null>(null);
  const [editingPriceId, setEditingPriceId] = useState<string | null>(null);
  const [balanceAdjustments, setBalanceAdjustments] = useState<Record<string, string>>({});

  const load = useCallback(async () => {
    setMessage('');
    if (mode === 'billing') {
      const data = await apiRequest<{ balanceCents: number; transactions: Transaction[]; recharges: Recharge[] }>('/api/billing/me');
      setBalance(data.balanceCents); setTransactions(data.transactions); setRecharges(data.recharges);
    } else {
      const [apiData, priceData, userData, rechargeData] = await Promise.all([
        apiRequest<{ apis: SystemApi[] }>('/api/admin/system-apis'),
        apiRequest<{ pricing: Pricing[] }>('/api/admin/pricing'),
        apiRequest<{ users: AuthUser[] }>('/api/admin/users'),
        apiRequest<{ recharges: Recharge[] }>('/api/admin/recharges'),
      ]);
      setApis(apiData.apis); setPricing(priceData.pricing); setUsers(userData.users); setRecharges(rechargeData.recharges);
    }
  }, [mode]);

  useEffect(() => { load().catch((error) => setMessage(error.message)); }, [load]);
  const act = async (job: () => Promise<unknown>, success: string) => { try { await job(); setMessage(success); await load(); await refresh(); } catch (error: any) { setMessage(error.message); } };

  return <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
    <button className="absolute inset-0 bg-black/70" onClick={onClose} aria-label="关闭" />
    <section className="relative w-full max-w-6xl max-h-[90vh] bg-dark-800 border border-dark-600 rounded-lg shadow-2xl flex flex-col overflow-hidden">
      <header className="h-14 px-5 border-b border-dark-600 flex items-center justify-between">
        <div><h2 className="text-white font-semibold flex items-center gap-2">{mode === 'billing' ? <Wallet className="w-5 h-5 text-green-400" /> : <Shield className="w-5 h-5 text-primary-400" />}{mode === 'billing' ? '余额与人工充值' : '系统管理控制台'}</h2><p className="text-[11px] text-dark-400 mt-0.5">当前身份：{user?.role === 'system' ? '系统用户（拥有管理权限）' : '普通用户'}</p></div>
        <div className="flex gap-1"><button onClick={() => load()} className="p-2 text-dark-400 hover:text-white" title="刷新"><RefreshCw className="w-4 h-4" /></button><button onClick={onClose} className="p-2 text-dark-400 hover:text-white" title="关闭"><X className="w-4 h-4" /></button></div>
      </header>
      <div className="overflow-y-auto p-5 space-y-6">
        {message && <div className="px-3 py-2 bg-dark-900 border border-dark-600 rounded text-sm text-dark-200">{message}</div>}
        {mode === 'billing' ? <>
          <div className="grid md:grid-cols-[1fr_2fr] gap-5">
            <div><div className="text-xs text-dark-400">当前余额</div><div className="text-3xl text-white font-semibold mt-1">{yuan(balance)}</div><div className="mt-5 p-3 rounded border border-amber-500/30 bg-amber-500/5 text-xs text-amber-200">微信支付和支付宝商户支付尚未接入。这里提交的是人工充值申请，不会跳转到微信或支付宝，也不会自动到账。</div><div className="mt-4 space-y-2"><input className={field} type="number" min="1" max="100000" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="申请入账金额（元）" /><textarea className={field} value={note} onChange={(e) => setNote(e.target.value)} placeholder="付款方式、流水号或审核说明" /><button className="w-full py-2 bg-primary-600 hover:bg-primary-500 rounded text-white text-sm" onClick={() => act(() => apiRequest('/api/billing/recharges', { method: 'POST', body: JSON.stringify({ amountCents: Math.round(Number(amount) * 100), note }) }), '人工充值申请已提交。系统用户需进入“系统管理 → 充值审核”确认后才会入账')}>提交人工充值申请</button><p className="text-xs text-dark-500">审核路径：系统用户登录 → 首页右上角“系统管理” → “充值审核” → 通过或拒绝。</p></div></div>
            <div><h3 className="text-sm text-white mb-2">余额流水</h3><div className="divide-y divide-dark-700">{transactions.map((item) => <div key={item.id} className="py-2 flex justify-between text-sm"><span className="text-dark-300">{item.description}<small className="block text-dark-500">{new Date(item.createdAt).toLocaleString()}</small></span><span className={item.amountCents >= 0 ? 'text-green-400' : 'text-red-400'}>{item.amountCents >= 0 ? '+' : ''}{yuan(item.amountCents)}</span></div>)}</div></div>
          </div>
          <div><h3 className="text-sm text-white mb-2">充值申请</h3><div className="divide-y divide-dark-700">{recharges.map((item) => <div key={item.id} className="py-2 flex justify-between text-sm text-dark-300"><span>{yuan(item.amountCents)} · {item.note || '无备注'}</span><span>{item.status === 'pending' ? '待审核' : item.status === 'approved' ? '已通过' : '已拒绝'}</span></div>)}</div></div>
        </> : <>
          <div className="grid md:grid-cols-[1fr_auto] gap-4 items-center p-4 border border-primary-500/30 bg-primary-500/5 rounded"><div><div className="text-sm font-medium text-white">系统用户专属管理区</div><p className="text-xs text-dark-300 mt-1">只有系统用户能看到此页面。充值申请必须由这里的系统用户明确点击“通过”后才会增加余额。</p></div><div className="px-3 py-2 rounded bg-dark-900 text-sm text-amber-300">待审核 {recharges.filter((item) => item.status === 'pending').length} 笔</div></div>
          <section><h3 className="text-sm font-medium text-white mb-3">系统 API</h3><div className="grid md:grid-cols-4 gap-2"><input className={field} value={apiForm.name} onChange={(e) => setApiForm({ ...apiForm, name: e.target.value })} placeholder="名称" /><input className={field} value={apiForm.provider} onChange={(e) => setApiForm({ ...apiForm, provider: e.target.value })} placeholder="服务商" /><input className={field} value={apiForm.baseUrl} onChange={(e) => setApiForm({ ...apiForm, baseUrl: e.target.value })} placeholder="HTTPS API 根地址" /><div className="flex gap-2"><input className={field} type="password" value={apiForm.apiKey} onChange={(e) => setApiForm({ ...apiForm, apiKey: e.target.value })} placeholder={editingApiId ? '留空则不修改 Key' : 'API Key'} /><button title={editingApiId ? '保存' : '添加'} className="px-3 bg-primary-600 rounded text-white" onClick={() => act(async () => { await apiRequest(editingApiId ? `/api/admin/system-apis/${editingApiId}` : '/api/admin/system-apis', { method: editingApiId ? 'PUT' : 'POST', body: JSON.stringify(apiForm) }); setApiForm({ name: '', provider: '', baseUrl: '', apiKey: '' }); setEditingApiId(null); }, editingApiId ? '系统 API 已更新' : '系统 API 已添加')}>{editingApiId ? <Check className="w-4 h-4" /> : <Plus className="w-4 h-4" />}</button></div></div><div className="mt-3 divide-y divide-dark-700">{apis.map((api) => <div key={api.id} className="py-2 grid md:grid-cols-[1fr_1.2fr_2fr_auto] gap-3 items-center text-sm"><span className="text-white">{api.name}<small className="block text-dark-500">{api.provider}</small></span><code className="text-dark-300 truncate">{showKeys[api.id] ? api.apiKey : '••••••••••••'}</code><span className="text-dark-400 truncate">{api.baseUrl}</span><div className="flex"><button title={showKeys[api.id] ? '隐藏' : '显示'} onClick={() => setShowKeys({ ...showKeys, [api.id]: !showKeys[api.id] })} className="p-2 text-dark-400">{showKeys[api.id] ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button><button title="复制" onClick={() => navigator.clipboard.writeText(api.apiKey)} className="p-2 text-dark-400"><Copy className="w-4 h-4" /></button><button title="编辑" onClick={() => { setEditingApiId(api.id); setApiForm({ name: api.name, provider: api.provider, baseUrl: api.baseUrl, apiKey: '' }); }} className="p-2 text-primary-400"><Pencil className="w-4 h-4" /></button><button title="删除" onClick={() => act(() => apiRequest(`/api/admin/system-apis/${api.id}`, { method: 'DELETE' }), 'API 已删除')} className="p-2 text-red-400"><Trash2 className="w-4 h-4" /></button></div></div>)}</div></section>
          <section><h3 className="text-sm font-medium text-white mb-3">模型定价</h3><div className="grid md:grid-cols-6 gap-2"><select className={field} value={priceForm.apiId} onChange={(e) => setPriceForm({ ...priceForm, apiId: e.target.value })}><option value="">选择 API</option>{apis.map((api) => <option key={api.id} value={api.id}>{api.name}</option>)}</select><input className={field} value={priceForm.modelId} onChange={(e) => setPriceForm({ ...priceForm, modelId: e.target.value })} placeholder="模型 ID" /><input className={field} value={priceForm.displayName} onChange={(e) => setPriceForm({ ...priceForm, displayName: e.target.value })} placeholder="显示名称" /><select className={field} value={priceForm.category} onChange={(e) => setPriceForm({ ...priceForm, category: e.target.value })}><option value="text">文本</option><option value="image">图片</option><option value="video">视频</option></select><select className={field} value={priceForm.billingUnit} onChange={(e) => setPriceForm({ ...priceForm, billingUnit: e.target.value })}><option value="request">按次</option><option value="image">按张</option><option value="second">按秒</option></select><div className="flex gap-2"><input className={field} type="number" min="0" step="0.01" value={priceForm.priceYuan} onChange={(e) => setPriceForm({ ...priceForm, priceYuan: e.target.value })} placeholder="单价（元）" /><button title={editingPriceId ? '保存定价' : '添加定价'} className="px-3 bg-primary-600 rounded text-white" onClick={() => act(async () => { await apiRequest(editingPriceId ? `/api/admin/pricing/${editingPriceId}` : '/api/admin/pricing', { method: editingPriceId ? 'PUT' : 'POST', body: JSON.stringify({ ...priceForm, unitPriceCents: Math.round(Number(priceForm.priceYuan) * 100) }) }); setEditingPriceId(null); }, editingPriceId ? '模型定价已更新' : '模型定价已添加')}>{editingPriceId ? <Check className="w-4 h-4" /> : <Plus className="w-4 h-4" />}</button></div></div><div className="mt-3 divide-y divide-dark-700">{pricing.map((item) => <div key={item.id} className="py-2 flex justify-between text-sm"><span className="text-dark-200">{item.displayName} <small className="text-dark-500">{item.modelId} · {item.category}</small></span><span className="flex items-center gap-3 text-green-400">{yuan(item.unitPriceCents)} / {item.billingUnit === 'second' ? '秒' : item.billingUnit === 'image' ? '张' : '次'}<button title="编辑" className="text-primary-400" onClick={() => { setEditingPriceId(item.id); setPriceForm({ apiId: item.apiId, modelId: item.modelId, displayName: item.displayName, category: item.category, billingUnit: item.billingUnit, priceYuan: String(item.unitPriceCents / 100) }); }}><Pencil className="w-4 h-4" /></button><button title="删除" className="text-red-400" onClick={() => act(() => apiRequest(`/api/admin/pricing/${item.id}`, { method: 'DELETE' }), '定价已删除')}><Trash2 className="w-4 h-4" /></button></span></div>)}</div></section>
          <section className="grid lg:grid-cols-2 gap-6"><div><h3 className="text-sm font-medium text-white mb-2">用户、权限与余额</h3><div className="divide-y divide-dark-700">{users.map((item) => <div key={item.id} className="py-2 grid grid-cols-[1fr_auto] gap-2 items-center text-sm"><span className="text-dark-200">{item.username}<small className="block text-dark-500">{item.email} · {yuan(item.balanceCents)}</small></span><div className="flex gap-2"><div className="flex"><input className="w-24 px-2 py-1 bg-dark-900 border border-dark-600 rounded-l text-white" type="number" step="0.01" value={balanceAdjustments[item.id] || ''} onChange={(e) => setBalanceAdjustments({ ...balanceAdjustments, [item.id]: e.target.value })} placeholder="增减元" /><button title="调整余额" className="px-2 bg-dark-700 border border-dark-600 rounded-r text-green-400" onClick={() => act(() => apiRequest(`/api/admin/users/${item.id}/balance`, { method: 'POST', body: JSON.stringify({ amountCents: Math.round(Number(balanceAdjustments[item.id]) * 100), description: '系统后台调整余额' }) }), '用户余额已调整')}><Coins className="w-4 h-4" /></button></div><select className="bg-dark-900 border border-dark-600 rounded px-2 py-1 text-dark-200" disabled={item.id === user?.id} value={item.role} onChange={(e) => act(() => apiRequest(`/api/admin/users/${item.id}/role`, { method: 'PATCH', body: JSON.stringify({ role: e.target.value }) }), '用户角色已更新')}><option value="user">普通用户</option><option value="system">系统用户</option></select></div></div>)}</div></div><div><h3 className="text-sm font-medium text-white mb-2">充值审核</h3><div className="divide-y divide-dark-700">{recharges.filter((item) => item.status === 'pending').map((item) => <div key={item.id} className="py-2 flex justify-between items-center text-sm"><span className="text-dark-200">{item.user?.username || item.user?.email}<small className="block text-dark-500">{yuan(item.amountCents)} · {item.note || '无备注'}</small></span><div className="flex gap-1"><button title="通过" className="p-2 text-green-400" onClick={() => act(() => apiRequest(`/api/admin/recharges/${item.id}/review`, { method: 'POST', body: JSON.stringify({ decision: 'approved' }) }), '充值已入账')}><Check className="w-4 h-4" /></button><button title="拒绝" className="p-2 text-red-400" onClick={() => act(() => apiRequest(`/api/admin/recharges/${item.id}/review`, { method: 'POST', body: JSON.stringify({ decision: 'rejected' }) }), '充值申请已拒绝')}><X className="w-4 h-4" /></button></div></div>)}</div></div></section>
        </>}
      </div>
    </section>
  </div>;
}
